---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
## Loading required packages

library(p8105.datasets)
library(flexdashboard)
library(tidyverse)
library(viridis)
library(p8105.datasets)

library(plotly)

```

Column {data-width=650}
-----------------------------------------------------------------------

### Aisle v.s. Order Number

```{r}
#Set the seed to make every sample the same
set.seed(1)

#Read the dataset
data(instacart)

#Because the dataset is too big, only read 5000 observations. 
instacart = instacart %>%
  sample_n(5000)

#Group the dataset by department and draw the orders in each aisle. 
instacart %>%
  group_by(department, aisle) %>% 
  summarize(n = n()) %>% 
  mutate(aisle = forcats::fct_reorder(factor(aisle), n, .desc = F)) %>% 
  
  #Use plotly. 
  plot_ly(x = ~aisle, y = ~n, color = ~department, type = "bar") %>%
  layout(
    title = "Number of Order in Each Aisle",
    scene = list(
      xaxis = list(title = "Aisle"),
      yaxis = list(title = "Interval")
    ))
  
  
  
```



Column {data-width=350}
-----------------------------------------------------------------------

### Interval between Orders for Each Aisle

```{r}

#Draw the intervals bettwen orders for each aisle. 
instacart %>% 
  group_by(aisle) %>% 
  summarize(interval = mean(days_since_prior_order)) %>% 
  mutate(aisle = forcats::fct_reorder(factor(aisle), interval, .desc = F)) %>%
  plot_ly(x = ~aisle, y = ~interval, type = "bar",
          colors = "Set2") %>%
  layout(
    title = "Intervals between Orders for Each Aisle",
    scene = list(
      xaxis = list(title = "Aisle"),
      yaxis = list(title = "Interval")
    ))
```

### Order Hour For Different Department

```{r}
#Draw the average order hour for each department. 
instacart %>% 
  group_by(department) %>% 
  plot_ly(x = ~department, y = ~order_hour_of_day, color = ~department, type = "box", colors = "Set2") %>%
  layout(
    title = "Order Hour For Different Department",
    scene = list(
      xaxis = list(title = "Departments"),
      yaxis = list(title = "Order Hour")
    ))



```

